config/routes.rb
Rails.application.routes.draw do
  root 'store#index'

  post 'orders/add_item', 'orders#add_item'
  get 'orders/show', 'orders#show'
  get 'orders/checkout', 'orders#checkout'
  patch 'orders/update', 'orders#update'

  resources :order_items, only: [:edit, :update, :destroy]
  resources :invoices, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :shipping_mode, optional: true
  has_many :order_items
  has_many :products, through: :order_items

  validates :name, presence: true, on: :update
  validates :email, presence: true, on: :update
  validates :address, presence: true, on: :update
  validates :shipping_mode, presence: true, on: :update

  enum status: [:in_progress, :ordered]

  def total_products_price
    total = 0
    order_items.each do |order_item|
      total = total + order_item.total_price
    end
    total
  end

  def total_tax
    total_products_price * 0.013
  end

  def total_price
    total_products_price + total_tax + shipping_mode.price
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true,
                       numericality: { greater_than_or_equal_to: 1 }

  def total_price
    product.price.to_f * quantity.to_f
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :price, presence: true,
                    numericality: { greater_than_or_equal_to: 0 }
end

app/models/shipping_mode.rb
class ShippingMode < ApplicationRecord
  has_many :orders

  validates :title, presence: true,
                    uniqueness: true

  validates :price, presence: true,
                    numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_order

  private

  def current_order
    if session[:order_id]
      order = Order.find_by(id: session[:order_id], status: :in_progress)

      if order
        return order
      end
    end

    order = Order.create
    session[:order_id] = order.id
    order
  end

  def handle_ar_messages(ar_object)
    handler = Handlers::ActiveRecordMessageHandler.new
    handler.handle(ar_object)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def show
    @order = Order.find(params[:id])

    if @order.in_progress?
      redirect_to orders_show_path
    end
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def edit
    @order_item = OrderItem.find(params[:id])
  end

  def update
    endpoint = Endpoints::OrderItems::UpdateEndpoint.new

    order_item = endpoint.perform(
      id: params[:id].to_i,
      quantity: params[:quantity].to_i
    )

    redirect_to orders_show_path, notice: handle_ar_messages(order_item)
  end

  def destroy
    endpoint = Endpoints::OrderItems::DestroyEndpoint.new

    order_item = endpoint.perform(id: params[:id].to_i) 

    redirect_to orders_show_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = current_order
  end

  def checkout
    @order = current_order
  end

  def update
    endpoint = Endpoints::Orders::UpdateEndpoint.new

    order = endpoint.perform(
      id: current_order.id,
      name: params[:name],
      email: params[:email],
      address: params[:address],
      shipping_mode_id: params[:shipping_mode_id].to_i,
      status: :ordered
    )

    redirect_to invoice_path(order.id), notice: handle_ar_messages(order)
  end

  def add_item
    endpoint = Endpoints::Orders::AddProductToOrderEndpoint.new

    order = endpoint.perform(
      order: current_order,
      product_id: params[:product_id].to_i,
      quantity: params[:quantity].to_i
    )

    redirect_to root_path, notice: handle_ar_messages(order)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    endpoint = Endpoints::Products::IndexEndpoint.new

    @products = endpoint.perform(page: params[:page].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invoices/_invoice_header.html.erb
<div class="row">
  <div class="col">
    Name: <%= order.name %>
  </div>
  <div class="col">
    Address: <%= order.address %>
  </div>
  <div class="col">
    Shipping Mode: <%= order.shipping_mode.title %>
  </div>
</div>
<hr>

app/views/invoices/_total_invoice.html.erb
<div class="row">
  <h2>Payment Details</h2>

  <table class="table">
    <tr>
      <td>Subtotal</td>
      <td><%= order.total_products_price %></td>
    </tr>
    <tr>
      <td>Taxes</td>
      <td><%= order.total_tax %></td>
    </tr>
    <tr>
      <td>Shipping</td>
      <td><%= order.shipping_mode.price %></td>
    </tr>
    <tr>
      <td><strong>Total</strong></td>
      <td><strong><%= order.total_price %></strong></td>
    </tr>
  </table>
</div>

app/views/invoices/show.html.erb
<h1>Invoice from order #<%= @order.id %></h1>

<%= render 'invoices/invoice_header', { order: @order } %>

<h2>Products</h2>
<%= render 'order_items/order_item_list', { order: @order, actions: false } %>

<%= render 'invoices/total_invoice', { order: @order } %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Eccomerce Prototype</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Products', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Order', orders_show_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommercePrototypeRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/order_items/_order_item_list.html.erb
<table class="table table-striped mt-4">
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total Line</th>
      <% if actions %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |order_item| %>
      <tr>
        <%= render 'order_items/order_item_row', { order_item: order_item, actions: actions } %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/order_items/_order_item_row.html.erb
<td><%= order_item.product.title %></td> 
<td><%= order_item.product.price %></td>
<td><%= order_item.quantity %></td>
<td><%= order_item.total_price %></td>
<% if actions %>
  <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
  <td>
    <%= link_to 'Delete', 
      url_for(controller: :order_items, action: :destroy, id: order_item.id),
      method: :delete,
      data: { confirm: 'Are you sure?' }
    %>
  </td>
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/edit.html.erb
<h1>Edit Order Item</h1>

<%= form_tag order_item_path, method: :patch do %>
  <%= number_field_tag :quantity, @order_item.quantity, { min: 1 } %>

  <%= submit_tag 'Update' %>
<% end %>

app/views/orders/_checkout_form.html.erb
<%= form_tag orders_update_path, method: :patch do %>
  <%= label_tag :name, nil, class: 'mt-3' %>
  <%= text_field_tag :name, nil, class: 'form-control' %>
  <%= label_tag :email, nil, class: 'mt-3' %>
  <%= email_field_tag :email, nil, class: 'form-control' %>
  <%= label_tag :address, nil, class: 'mt-3' %>
  <%= text_field_tag :address, nil, class: 'form-control' %>
  <%= label_tag :shipping_mode, nil, class: 'mt-3'%>
  <%= select_tag :shipping_mode_id, 
    options_from_collection_for_select(
      ShippingMode.all,
      :id,
      :title
  ),
  class: 'form-control'
%>

  <%= submit_tag 'Order', class: 'btn btn-success btn-block mt-4' %>
<% end %>

app/views/orders/checkout.html.erb
<h1 class="mt-3">Checkout</h1>

<%= render 'orders/checkout_form' %>

<h2 class="mt-4">Products</h2>

<%= render 'order_items/order_item_list', { order: @order, actions: false } %>

app/views/orders/show.html.erb
<h1 class="mt-3">Order</h1>
<hr>

<div class="row mt-4">
  <div class="col-6">
    <h3>List of Products</h3>
  </div>
  <div class="col-3">
    Total: <%= @order.total_products_price %>
  </div>
  <div class="col-3">
    <%= link_to 'Checkout', orders_checkout_path, class: 'btn btn-secondary' %>
  </div>
</div>

<%= render 'order_items/order_item_list', { order: @order, actions: true } %>

app/views/products/_product.html.erb
<div class="col">
  <div class="card" style="width: 18rem;">
    <%= image_tag product.image_url, class:'card-img-top' %>
    <div class="card-body">
      <h5 class="card-title"><%= product.title %></h5>
      <p class="card-text">Price: <%= product.price %></p>

      <%= form_tag orders_add_item_path, method: :post do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, {}, { min: 1, class: 'form-control' } %>

        <%= submit_tag 'Buy', class: 'btn btn-success btn-block mt-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/store/index.html.erb
<h1 class="mt-3">Products</h1>

<% @products.to_a.in_groups_of(3, false) do |products| %>
  <div class="row mt-3 ">
    <% products.each do |product| %>
      <%= render 'products/product', product: product %>
    <% end %>
  </div>
<% end %>

<div class="paginator mt-3">
  <%= paginate @products %>
</div>